import test from 'node:test';
import assert from 'node:assert/strict';
import { convert, validAddress } from '../src/converter.js';
const a='0xa8bc99324c7d69533ae5fd2c4a9bb8a58be9e02a';
test('BasedBot screenshot style preserves emoji, spaces and group text',()=>{const r=convert(`${a}  👀  nhk06.eth Cabal`,'basedbot','gmgn');assert.deepEqual(JSON.parse(r.output),[{address:a,emoji:'👀',name:'nhk06.eth Cabal',groups:[]}]);});
test('GMGN export accepts alert settings and merges group labels',()=>{const r=convert(JSON.stringify([{address:a,name:'Alpha Whale',emoji:'👨‍💻',groups:['Cabal'],alertsOnToast:true,sound:'default'}]),'gmgn','basedbot');assert.equal(r.output,`${a}  👨‍💻  Alpha Whale  Cabal`);assert.equal(r.warnings.length,1);});
test('roundtrip keeps names and compound emojis',()=>{for(const emoji of ['👨‍💻','🇮🇩','👍🏽','1️⃣']){const input=`${a}  ${emoji}  long wallet name`;const r=convert(input,'basedbot','gmgn');assert.equal(convert(r.output,'gmgn','basedbot').output,input);}});
test('empty input, CRLF and empty labels',()=>{assert.equal(convert('','basedbot','gmgn').count,0);assert.equal(convert(`\r\n${a}\r\n`,'basedbot','gmgn').count,1);assert.equal(convert(JSON.stringify([{address:a}]),'gmgn','basedbot').output,a);});
test('invalid addresses and malformed records block entire export',()=>{for(const input of ['[','{}','[null]',JSON.stringify([{address:a},{address:'0x123'}]),JSON.stringify([{address:a,name:22}]),JSON.stringify([{address:a,groups:'foo'}]),JSON.stringify([{address:a,name:'bad\nlabel'}])])assert.throws(()=>convert(input,'gmgn','basedbot'));assert.throws(()=>convert(`${a}\n0x123 bad`,'basedbot','gmgn'));});
test('duplicates retained and flagged without modifying addresses',()=>{const r=convert(`${a}\n${a.toUpperCase().replace('0X','0x')}`,'basedbot','gmgn');assert.equal(r.count,2);assert.equal(r.warnings.length,1);});
test('2000 wallet boundary enforced',()=>{assert.equal(convert(Array(2000).fill(a).join('\n'),'basedbot','gmgn').count,2000);assert.throws(()=>convert(Array(2001).fill(a).join('\n'),'basedbot','gmgn'));});
test('EVM and 32 byte Solana address validation',()=>{assert.ok(validAddress(a));assert.ok(validAddress('11111111111111111111111111111111'));assert.ok(validAddress('So11111111111111111111111111111111111111112'));assert.ok(!validAddress('111111111111111111111111111111111'));assert.ok(!validAddress('0xdeadbeef'));});
test('Fomo explicitly unavailable',()=>assert.throws(()=>convert(a,'fomo','gmgn')));
